"""ondeckdata_table

Revision ID: 5e4898954923
Revises: 17911f3ffb3b
Create Date: 2023-06-05 14:09:26.594081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4898954923'
down_revision = '17911f3ffb3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ondeckdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_uri', sa.String(), nullable=True),
    sa.Column('cocoannotations_uri', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ondeckdata')
    # ### end Alembic commands ###
