"""s3uploadstable

Revision ID: 677a2f2884e1
Revises: 97b633de0899
Create Date: 2023-08-02 17:08:34.590190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677a2f2884e1'
down_revision = '97b633de0899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('s3uploads',
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tablename', sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3uploads')
    # ### end Alembic commands ###
