"""gps_data_types

Revision ID: 81b92a299311
Revises: ecb326942445
Create Date: 2023-07-26 16:51:17.527649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81b92a299311'
down_revision = 'ecb326942445'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from gpsdata;")
    op.add_column('gpsdata', sa.Column('gps_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('gpsdata', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('gpsdata', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('gpsdata', 'sentence')
    op.drop_column('gpsdata', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from gpsdata;")
    op.add_column('gpsdata', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('gpsdata', sa.Column('sentence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gpsdata', 'lon')
    op.drop_column('gpsdata', 'lat')
    op.drop_column('gpsdata', 'gps_datetime')
    # ### end Alembic commands ###
