"""starttime_on_videos

Revision ID: ecb326942445
Revises: 1d1b10e054af
Create Date: 2023-07-20 16:58:45.490762

"""
from alembic import op
import sqlalchemy as sa

from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = 'ecb326942445'
down_revision = '1d1b10e054af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'video_files', 
        sa.Column('start_datetime', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
    op.execute("""
               update video_files 
               set start_datetime = to_timestamp(
                    substring(
                        original_path 
                        from '[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
                    ) || ' 00 00',
                'DD-MM-YYYY-HH24-MI TZH TZM'
               )
               """)
    op.alter_column(
        'video_files', 
        sa.Column('start_datetime', sa.DateTime(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_files', 'start_datetime')
    # ### end Alembic commands ###
